import QueryProvider from '@/providers/query-provider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <QueryProvider>
        <body className={inter.className}>
          <main className="flex min-h-screen flex-col items-center p-24">
            {children}
          </main>
        </body>
      </QueryProvider>
    </html>
  )
}
